### ISSUE TITLE
Publish Rubygem v1.2.0

### ISSUE THREAD

**Issue by rramsden** [maxmind/minfraud-api-ruby#33]
### Context

Hey all, it seems the latest version of `minfraud-api-ruby` is not published yet on Rubygems.
We're trying to use some new functionality and would appreciate if 1.2.0 can be published 🙏 

For now, we will continue to reference the master branch in our Gemfile.

**Comment by horgh** [comment]
Hi! Thank you for the reminder :-). I've published it now!
